site_name: ODIN
theme: readthedocs
repo_url: https://github.com/gcba-odin/odin-tech-docs
pages:
    - 'Home': 'index.md'
    - 'Key Features': 'key-features.md'
    - 'Arquitectura': 'arquitectura.md'
    - 'Codigo Fuente': 'codigo-fuente.md'
    - 'Metodología': 'metodologia.md'
    - Sprints:
        - 'Sprint 1': 'sprints/sprint1.md'
    - Links:
        - 'Backend': 'links/backend.md'
        - 'Frontend': 'links/frontend.md'