site_name: ODIN
theme: readthedocs
repo_url: https://github.com/gcba-odin/odin-tech-docs
pages:
    - 'Home': 'index.md'
    - 'Key Features': 'key-features.md'
    - 'Arquitectura': 'arquitectura.md'
    - 'Codigo Fuente': 'codigo-fuente.md'
    - 'Metodología': 'metodologia.md'
    - 'Entidades': 'entidades.md'
    - 'Responses': 'responses.md'
    - Sprints:
        - 'Sprint 1': 'sprints/sprint-1.md'
        - 'Sprint 2': 'sprints/sprint-2.md'
        - 'Sprint 3': 'sprints/sprint-3.md'
        - 'Sprint 4': 'sprints/sprint-4.md'
        - 'Sprint 5': 'sprints/sprint-5.md'
        - 'Sprint 6': 'sprints/sprint-6.md'
        - 'Sprint 7': 'sprints/sprint-7.md'
        - 'Sprint 8': 'sprints/sprint-8.md'
        - 'Sprint 9': 'sprints/sprint-9.md'
        - 'Sprint 10': 'sprints/sprint-10.md'
        - 'Sprint 11': 'sprints/sprint-11.md'
        - 'Sprint 12': 'sprints/sprint-12.md'
        - 'Sprint 13': 'sprints/sprint-13.md'
        - 'Sprint 14': 'sprints/sprint-14.md'
    - Referencias:
        - 'HTTP Status Codes': 'references/status-codes.md'
    - Links:
        - 'Backend': 'links/backend.md'
        - 'Frontend': 'links/frontend.md'